apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
spec:
  containers:
    - name: my-nignx-app
      image: mohamedkbx/nginx-test
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
